spring:
  cloud:
    gateway:
      routes:
        - id: userauth
          uri: http://localhost:9972
          predicates:
            - Path=/user-auth/**

        - id: history
          uri: http://localhost:9975
          predicates:
            - Path=/transactions/**


        - id: watchlist
          uri: http://localhost:9973
          predicates:
            - Path=/watchlist/**, /trending/**


        - id: performance
          uri: http://localhost:8085
          predicates:
            - Path=/share-prices/**


